/**
 * Project 073 — Authenticated UI copy (Simplified Chinese only).
 * Internal keys stay English; values are user-facing zh-CN.
 */

export const uiZh = {
  appName: "RIVA OS",

  // Shell / nav
  navHome: "首页",
  navCrm: "客户",
  navProjects: "项目",
  navFinance: "财务",
  navReports: "报表",
  navSettings: "设置",
  search: "搜索",
  searchUnavailable: "搜索暂不可用",
  notifications: "通知",
  aiAssistant: "AI 助手",
  aiAssistantSoon: "AI 助手即将推出",
  userProfile: "用户资料",
  profile: "个人资料",
  settings: "设置",
  signOut: "退出登录",
  signOutFailed: "退出登录失败",
  switchBusiness: "切换企业",

  // Company switcher
  selectCompany: "选择公司",
  companies: "公司",
  createCompany: "创建公司",
  manageCompanies: "管理公司",
  companySettings: "公司设置",
  switchedTo: (name: string) => `已切换至 ${name}`,

  // Workspace switcher
  selectWorkspace: "选择工作区",
  workspaces: "工作区",
  noWorkspacesYet: "暂无工作区",
  createWorkspace: "创建工作区",
  manageWorkspaces: "管理工作区",
  workspaceSettings: "工作区设置",
  pending: "待激活",
  suspended: "已暂停",

  // Home / Daily Workspace
  goodMorning: "早上好",
  goodAfternoon: "下午好",
  goodEvening: "晚上好",
  greetingGuest: "朋友",
  welcomeBack: "欢迎回来。",
  todaysFocus: "今日重点",
  todaysPriorities: "今日优先",
  todaysTasks: "今日任务",
  todaysMeetings: "今日会议",
  todaysDeadlines: "今日截止",
  nothingDueToday: "今日暂无任务",
  taskListClear: "今天的任务清单是空的。",
  noMeetingsToday: "今日暂无会议",
  calendarOpen: "今天的日程空闲。",
  noDeadlinesToday: "今日暂无截止事项",
  nothingOverdueOrDue: "没有逾期或今日到期的事项。",
  prioritiesAppear: "有需要关注的任务或会议时会显示优先事项。",
  quickActions: "快捷操作",
  newClient: "+ 新建客户",
  newProject: "+ 新建项目",
  newTask: "+ 新建任务",
  aiDailyBrief: "AI 每日简报",
  brief: "简报",
  recentActivity: "最近动态",
  noRecentActivity: "暂无最近动态",
  activityWillAppear: "有进展时会显示在这里。",

  // Briefs
  overdueTasks: (n: number) =>
    n === 1 ? "你有 1 个逾期任务。" : `你有 ${n} 个逾期任务。`,
  noMeetingsAfternoon: "今天下午没有会议。",
  clientNoReply: "客户 Carmen 已 5 天未回复。",
  dueToday: "今日到期",
  overdue: "已逾期",

  // Common
  cancel: "取消",
  save: "保存",
  create: "创建",
  edit: "编辑",
  delete: "删除",
  archive: "归档",
  restore: "恢复",
  back: "返回",
  loading: "加载中…",
  soon: "即将推出",
  required: "必填",
  optional: "可选",
  optionalParen: "（可选）",
  searchEllipsis: "搜索…",
  noPermission: "你没有权限查看此内容。",
  overview: "概览",
  status: "状态",
  owner: "负责人",
  name: "名称",
  description: "描述",
  actions: "操作",
  updated: "更新时间",
  created: "创建时间",
  email: "邮箱",
  emailPlaceholder: "请输入邮箱",
  phone: "电话",
  notes: "备注",
  gallery: "图库",
  packageTab: "套餐",
  financeComingSoon: "财务（即将推出）",
  schedule: "日程",
  company: "公司",
  workspace: "工作区",
  role: "角色",
  members: "成员",
  active: "进行中",
  inactive: "未启用",
  open: "打开",
  all: "全部",
  none: "无",
  newLabel: "新建",
  saving: "保存中…",
  saveChanges: "保存更改",
  saveSettings: "保存设置",
  deactivate: "停用",
  reactivate: "重新启用",
  suspend: "暂停",
  placeholderBadge: "占位",
  emDash: "—",
  countOfTotal: (shown: number, total: number) => `${shown} / ${total}`,
  tryDifferentSearch: "请尝试其他搜索词。",
  creating: "创建中…",
  uploading: "上传中…",
  upload: "上传",
  done: "完成",
  failed: "失败",
  you: "你",
  userFallback: "用户",
  activity: "动态",
  calendar: "日历",
  timeline: "时间线",
  finance: "财务",
  automation: "自动化",
  team: "团队",
  teamMembers: "团队成员",
  comments: "评论",
  history: "历史",
  preview: "预览",
  versionHistory: "版本历史",
  noActivityYet: "暂无动态",
  noCommentsYet: "暂无评论",
  noHistoryYet: "暂无历史",
  type: "类型",
  size: "大小",
  uploadedBy: "上传人",
  uploadedDate: "上传日期",
  backToList: (section: string) => `← ${section}`,
  updatedAtLabel: (date: string) => `更新于 ${date}`,
  dateFormatHint: "请使用 YYYY-MM-DD 格式",
  endDateAfterStart: "结束日期不能早于开始日期",
  validEmailRequired: "请输入有效邮箱",
  slug: "标识",
  timezone: "时区",
  locale: "语言区域",
  currency: "货币",
  countryIso: "国家（ISO）",
  logoUrl: "Logo 链接",
  website: "网站",
  address: "地址",
  contactPerson: "联系人",
  category: "类别",
  location: "地点",
  date: "日期",
  time: "时间",
  durationMinutes: "时长（分钟）",
  minutesShort: (n: number) => `${n} 分钟`,
  durationTbd: "时长待定",
  titleLabel: "标题",
  assignedOwner: "负责人",
  projectPrefix: "项目 ·",
  ownerPrefix: "负责人 ·",
  softArchiveOnly: "仅软归档 — 不会永久删除。",
  checkingSession: "正在验证会话",
  loadingWorkspace: "正在加载工作区…",
  dashboard: "首页",
  backToWorkspace: "返回工作区",
  sectionsCount: (n: number) => `${n} 个分区`,
  settingsSectionsAria: "设置分区",
  systemActor: "系统",
  entityActorLine: (entityType: string, actor: string) =>
    `实体 ${entityType} · 操作者 ${actor}`,
  httpsPlaceholder: "https://…",
  noProject: "无项目",
  relatedProjectOptional: "关联项目（可选）",
  internalNotes: "内部备注",
  participants: "参与者",
  participantFallback: "参与者",
  participantN: (n: number) => `参与者 ${n}`,
  agenda: "议程",
  decisions: "决议",
  attachments: "附件",
  documents: "文档",
  identity: "身份",
  displayName: "显示名称",
  userId: "用户 ID",
  activeContext: "当前上下文",
  defaults: "默认值",
  personalOverrides: "个人覆盖",
  channels: "渠道",
  inbox: "收件箱",
  theme: "主题",
  density: "密度",
  darkTheme: "深色",
  lightTheme: "浅色",
  themeActive: "当前",
  themePlanned: "计划中",
  password: "密码",
  sessions: "会话",
  companyProfile: "公司资料",
  workspaceProfile: "工作区资料",
  companyNameRequired: "请填写公司名称",
  workspaceNameRequired: "请填写工作区名称",
  vendorNameRequired: "请填写供应商名称",
  titleRequired: "请填写标题",
  dateRequired: "请填写日期",
  timeRequired: "请填写时间",
  companyCreated: "公司已创建",
  companyUpdated: "公司已更新",
  companySuspended: "公司已暂停",
  companyReactivated: "公司已重新启用",
  companyArchived: "公司已归档",
  companyRestored: "公司已恢复",
  workspaceCreated: "工作区已创建",
  workspaceUpdated: "工作区已更新",
  workspaceSuspended: "工作区已暂停",
  workspaceArchived: "工作区已归档",
  workspaceRestored: "工作区已恢复",
  vendorCreated: "供应商已创建",
  vendorUpdated: "供应商已更新",
  vendorDeactivated: "供应商已停用",
  vendorArchived: "供应商已归档",
  vendorRestored: "供应商已恢复",
  meetingCompletedToast: "会议已完成",
  meetingCancelledToast: "会议已取消",
  completeAction: "完成",
  cancelMeeting: "取消会议",
  upcoming: "即将到来",
  scheduled: "已安排",
  confirmed: "已确认",
  noShow: "未出席",
  unspecified: "未指定",
  customDomain: "自定义域名",
  notConfigured: "未配置。",
  currentStatus: (status: string) => `当前：${status}`,
  currentDomain: (domain: string) => `当前：${domain}`,
  editSettingsFor: (entityName: string) => `编辑 ${entityName} 的设置。`,
  viewingNoWriteAccess: (entityName: string) =>
    `正在查看 ${entityName}。你没有写入权限。`,
  noPermissionEditCompany: "你没有权限编辑此公司。",
  noPermissionMeetings: "你没有权限查看会议。",
  noPermissionVendors: "你没有权限查看供应商。",
  restoreWorkspace: "恢复工作区",
  archiveWorkspace: "归档工作区",
  workspaceStatus: "工作区状态",
  workspacesNeverDeleted: "。工作区不会被永久删除。",
  companyStatusHint: "。仅软归档 — 不会永久删除。",
  slugImmutable: "创建后标识不可更改（路由与未来自定义域名）。",
  logoUrlHint: "目前使用 HTTPS 链接。文件上传将随存储架构上线。",
  customDomainHint: "数据结构已就绪（custom_domain）。开通功能暂缓。",
  slugUniqueHint: "唯一 URL 标识，须在所有工作区中唯一。",
  createWorkspaceHint: "你将成为所有者。名称必填；标识须唯一。",
  manageCompaniesIn: (wsName: string) => `管理 ${wsName} 中的公司`,
  oneWorkspaceMultipleCompanies: "一个工作区可包含多家公司。",
  noCompaniesYet: "此工作区尚无公司。创建一家公司以开始使用。",
  addCompanyTo: (wsName: string) => `向 ${wsName} 添加公司`,
  workspacesPageDesc: "创建并切换工作区。仅软归档 — 不会永久删除。",
  noWorkspacesBelong: "你还不属于任何工作区。创建一个以开始使用。",
  reportsEyebrow: "报表",
  reportsTitle: "报表",
  reportsDesc: "活跃企业的洞察将显示在这里。",
  noReportsYet: "暂无报表",
  reportsEmptyDesc: "随着工作区成长，运营报表将出现在这里。",
  meetingScheduleFor: "会议安排 ·",
  vendorCrmFor: "供应商 CRM ·",
  scheduleMeetingFor: (bizName: string) => `为 ${bizName} 安排会议`,
  updateMeetingFor: (title: string) => `更新「${title}」的日程与关联。`,
  addVendorTo: (bizName: string) => `向 ${bizName} 添加供应商`,
  andAssignToProject: "并分配到此项目。",
  editMeeting: "编辑会议",
  editVendor: "编辑供应商",
  meetingWorkspace: "会议工作区",
  vendorWorkspace: "供应商工作区",
  allMeetings: "全部会议",
  meetingDetails: "会议详情",
  meetingDetailsDesc: "日程、关联与参与者",
  vendorDetails: "供应商详情",
  vendorDetailsDesc: "此供应商的联系方式、类别与归属",
  editDetails: "编辑详情",
  linkedProject: "关联项目",
  linkedProjectDesc: "此供应商的可选项目关联",
  noProjectLinked: "未关联项目。",
  starts: "开始",
  ends: "结束",
  googleMeet: "Google Meet",
  googleMeetLink: "Google Meet 链接",
  relatedVendors: "关联供应商",
  noVendorsAvailable: "暂无可用供应商。",
  participantsDesc: "受邀参加此会议的人员",
  noParticipantsListed: "暂无参与者。",
  participantsCount: (n: number) => `参与者（${n}）`,
  agendaCount: (n: number) => `议程（${n}）`,
  agendaDesc: "本次会议的讨论事项（按顺序）",
  noAgendaYet: "暂无议程。",
  decisionsCount: (n: number) => `决议（${n}）`,
  decisionsDesc: "带状态与负责人的结果",
  noDecisionsYet: "暂无决议。",
  decisionProposed: "提议",
  decisionAccepted: "已接受",
  decisionRejected: "已拒绝",
  decisionDeferred: "已延期",
  notesDraftDesc: "起草会议备注。富文本与保存即将推出。",
  writeMeetingNotes: "撰写会议备注…",
  localDraftOnly: "仅本地草稿 — 更改尚未保存。",
  attachmentsSoon: "接入存储后，会议文件将显示在这里。",
  activityAuditDesc: "会议变更的审计记录（会话缓冲）",
  vendorActivityAuditDesc: "供应商变更的审计记录（会话缓冲）",
  noAuditedChanges: "本会话尚无已审计的变更。",
  relatedMeetings: "相关会议",
  relatedMeetingsDesc: "与此供应商关联的会议",
  noRelatedMeetings: "暂无相关会议。",
  relatedDocuments: "相关文档",
  vendorDocumentsSoon: "接入文档持久化后，供应商文档将显示在这里。",
  relatedTimeline: "相关时间线",
  vendorTimelineSoon: "按供应商筛选时间线后，事件将显示在这里。",
  relatedFinance: "相关财务",
  vendorFinanceSoon: "此供应商的报价、发票与付款将显示在这里。",
  vendorNotesDesc: "此供应商的内部 CRM 备注",
  noNotesYet: "暂无备注。",
  updateNotesFromEdit: "请在「编辑详情」中更新备注。",
  linkVendorToProjectHint:
    "在「编辑详情」中将此供应商关联到项目后，即可在此查看。",
  vendorsCount: (n: number) => `供应商（${n}）`,
  noVendorsYet: "暂无供应商",
  addVendorsDesc: "添加摄影师、场地、餐饮等供应商。",
  addVendorsForCompany: "为此公司添加摄影师、场地、餐饮等供应商。",
  manageVendorsLink: "管理供应商 →",
  createVendor: "创建供应商",
  scheduleMeetingsDesc: "安排咨询、场地勘察与供应商讨论。",
  comingSoonModuleHint: "此模块尚未开放。请先使用项目、客户与供应商。",
  // Settings section bodies
  identityDesc: "来自身份验证的已登录账户信息。",
  activeContextDesc: "由会话上下文解析的工作区与公司。",
  profileEditingLater: "个人资料编辑稍后将接入人员目录。",
  securitySettingsLink: "安全设置 →",
  defaultsDesc: "在个人偏好持久化之前，继承自当前公司上下文。",
  personalOverridesDesc: "用户级偏好存储计划中。",
  personalOverridesBody:
    "尚未保存个人覆盖。上方数值在可用时反映当前公司。",
  channelsDesc: "应用内、邮件与摘要偏好将放在这里。",
  channelInApp: "应用内 — 已启用（预览）",
  channelEmail: "邮件 — 计划中",
  channelDigests: "摘要 — 计划中",
  inboxDesc: "浏览通知工作区预览。",
  openNotificationWorkspace: "打开通知工作区 →",
  themeDesc: "RIVA 当前使用深色指挥中心界面。",
  densityDesc: "仪表板默认使用舒适密度。",
  densityBody: "紧凑 / 舒适密度控制将挂接到此分区。",
  passwordDesc: "使用现有身份验证密码流程。",
  updatePasswordLink: "更新密码 →",
  sessionsDesc: "会话刷新与过期由身份验证中间件处理。",
  sessionTokenRefresh: "令牌刷新 — 中间件 + AuthSessionProvider",
  sessionSignOut: "退出登录 — 清除全局会话",
  sessionMultiDevice: "多设备会话列表 — 计划中",
  membersPlaceholderDesc:
    "成员角色与邀请将接入此处，且不会改动本项目的邀请系统。",
  integrationsPlaceholderDesc: "第三方连接器与 Webhook 稍后将出现在这里。",
  billingPlaceholderDesc: "套餐、发票与支付服务商刻意不在本期范围。",
  settingsProfileSectionDesc: "你的账户身份与联系方式。",
  settingsPreferencesSectionDesc: "语言区域、时区与个人默认值。",
  settingsNotificationsSectionDesc: "提醒与摘要的投递偏好。",
  settingsAppearanceSectionDesc: "主题与显示偏好。",
  settingsSecuritySectionDesc: "密码与会话控制。",
  settingsCompanySectionDesc: "当前公司资料与状态。",
  settingsWorkspaceSectionDesc: "当前工作区资料与状态。",
  settingsMembersSectionDesc: "成员与角色（即将推出）。",
  settingsIntegrationsSectionDesc: "已连接服务与 API 钩子。",
  settingsBillingSectionDesc: "套餐与发票。",
  // Meeting type / status labels
  meetingTypeFollowUp: "跟进",
  meetingTypeVenueVisit: "场地勘察",
  meetingTypeVendorDiscussion: "供应商讨论",
  meetingTypeInternal: "内部会议",
  meetingTypeRehearsal: "婚礼彩排",
  meetingTypeConsultation: "咨询",
  meetingTypeOther: "其他",
  // Vendor categories
  vendorPhotographer: "摄影师",
  vendorVideographer: "摄像师",
  vendorDecorator: "布置",
  vendorMakeupArtist: "化妆师",
  vendorLiveBand: "乐队",
  vendorEmcee: "司仪",
  vendorVenue: "场地",
  vendorCatering: "餐饮",
  vendorFlorist: "花艺",
  vendorOthers: "其他",
  // Company types
  companyTypeAgency: "机构",
  companyTypeBrand: "品牌",
  companyTypeVenue: "场地",
  companyTypeCorporate: "企业",
  companyTypeWedding: "婚礼",
  companyTypeOther: "其他",
  // Form placeholders
  placeholderWorkspaceName: "示例活动",
  placeholderWorkspaceSlug: "example-events",
  placeholderCountry: "CN",
  participantsPlaceholder: "每行一项：姓名 | 角色 | 邮箱",
  companyNameLabel: "公司名称",

  // CRM
  crm: "客户",
  clients: "客户",
  clientDirectoryFor: (business: string) => `${business} 的客户目录`,
  searchClients: "搜索客户…",
  noClientsYet: "暂无客户",
  addFirstClient: "添加第一位客户，开始建立客户关系。",
  noMatchingClients: "没有匹配的客户",
  clientName: "客户名称",
  clientNameRequired: "请填写客户名称",
  clientInformation: "客户信息",
  clientCreated: "客户已创建",
  clientUpdated: "客户已更新",
  clientProfile: "客户资料",
  newClientTitle: "新建客户",
  editClient: "编辑客户",
  createClient: "创建客户",
  createClientDesc: "向此企业添加客户，仅名称必填。",
  addClientTo: (business: string) => `向 ${business} 添加客户。`,
  projectCount: "关联项目",
  followUp: "跟进",
  vendors: "供应商",
  companyName: "公司名称",
  companyOptional: "公司",
  optionalNotes: "可选备注",
  noPermissionClients: "你没有权限查看客户。",
  noPermissionFinance: "你没有权限查看财务。",
  clientActivitySoon: "客户动态将在后续更新中显示。",
  linkedProjectsSoon: "关联项目将在后续更新中显示。",
  extendedNotesSoon: "扩展备注与时间线备注将在后续显示。",
  noAdditionalNotes: "暂无更多备注",
  clientStatusActive: "活跃",
  clientStatusFollowUp: "跟进",
  clientStatusArchived: "已归档",
  clientStatusInquiry: "询盘",
  clientStatusConfirmed: "已确认",
  clientStatusCompleted: "已完成",
  clientStatusCancelled: "已取消",
  clientTypeWedding: "婚礼",
  clientTypeCorporate: "企业",
  clientTypePrivate: "私人",
  clientTypeOthers: "其他",
  clientSource: "来源",
  leadOwner: "线索负责人",
  assignedPic: "对接人",
  whatsapp: "WhatsApp",
  instagram: "Instagram",
  facebook: "Facebook",
  homeAddress: "家庭住址",
  city: "城市",
  state: "州/省",
  country: "国家",
  birthday: "生日",
  anniversary: "纪念日",
  weddingDate: "婚期",
  weddingType: "婚礼类型",
  weddingSession: "场次",
  includeRom: "ROM",
  includeLunch: "午宴",
  includeDinner: "晚宴",
  ballroom: "宴会厅",
  expectedPax: "预计人数",
  clientBudget: "客户预算",
  religion: "宗教",
  language: "语言",
  filterActive: "启用",
  filterInactive: "停用",
  filterAllStatuses: "全部状态",
  filterAllTypes: "全部类型",
  createWeddingProject: "创建婚礼项目",
  projectCode: "项目编号",
  clientCode: "客户编号",
  coordinator: "统筹",
  planner: "策划",
  salesPersonLabel: "销售",
  packageName: "套餐",
  countdown: "倒计时",
  daysUntilWedding: (days: number) => `还有 ${days} 天`,
  weddingPassed: "已举办",
  latestActivity: "最近动态",
  recentFiles: "最近文件",
  upcomingTasks: "即将到来的任务",
  couple: "新人",
  projectWorkspaceReady: "项目工作区已就绪，可连接后续模块。",
  comingSoonModule: "此模块即将推出。",
  noUpcomingTasks: "暂无任务",

  // Project 099 — Wedding Timeline Builder
  timelineBuilder: "婚礼时间线",
  tlViewTimeline: "时间线",
  tlViewTable: "表格",
  tlViewList: "列表",
  tlViewWeddingDay: "婚礼当天",
  tlViewPrint: "打印预览",
  tlViewCalendar: "日历",
  tlViewGantt: "甘特图（即将推出）",
  tlCalendarDayAgenda: "当日日程",
  tlCalendarWeddingDay: "婚礼日",
  tlCalendarNoWeddingDate: "未设置婚礼日期 — 显示全部时段活动",
  tlCalendarNoItems: "无活动",
  tlCalendarSelectWeddingHint: "请选择婚礼日查看时间线日程",
  tlCalendarJumpWedding: "跳转到婚礼日",
  tlCalendarAddAtHour: "在此时段添加…",
  tlCalendarUntimed: "未定时活动",
  tlAddItem: "添加时间点",
  tlImport: "导入",
  tlExport: "导出",
  tlGeneratePdf: "生成 PDF",
  tlSearch: "搜索时间线…",
  tlProgress: "进度",
  tlStartTime: "开始",
  tlEndTime: "结束",
  tlDuration: "时长",
  tlActivity: "活动",
  tlCategory: "分类",
  tlLocation: "地点",
  tlPic: "负责人",
  tlVendor: "供应商",
  tlCoordinator: "统筹",
  tlCrew: "团队",
  tlPriority: "优先级",
  tlReminder: "提醒",
  tlAttachments: "附件",
  tlInternalNotes: "内部备注",
  tlChecklist: "检查清单",
  tlDuplicate: "复制",
  tlMoveUp: "上移",
  tlMoveDown: "下移",
  tlShiftFollowing: "顺延后续活动",
  tlItemOnly: "仅移动此项",
  tlBulkActions: "批量操作",
  tlEmpty: "暂无时间线项目",
  tlEmptyHint: "添加第一个活动，开始编排婚礼当天流程。",
  tlItemSaved: "时间线已保存",
  tlItemCreated: "时间点已创建",
  tlItemDeleted: "时间点已删除",
  tlComingSoonAction: "即将推出",
  tlCurrentActivity: "当前活动",
  tlNextActivity: "下一个活动",
  tlComplete: "完成",
  tlDelay: "延迟",
  tlPrevious: "上一项",
  tlNext: "下一项",
  tlPrintMaster: "主时间线",
  tlPrintCoordinator: "统筹版",
  tlPrintMc: "司仪版",
  tlPrintVendor: "供应商版",
  tlNoPermission: "你没有权限查看时间线。",
  tlStatusNotStarted: "未开始",
  tlStatusReady: "就绪",
  tlStatusInProgress: "进行中",
  tlStatusCompleted: "已完成",
  tlStatusDelayed: "延迟",
  tlStatusCancelled: "已取消",
  tlPriorityLow: "低",
  tlPriorityNormal: "普通",
  tlPriorityHigh: "高",
  tlPriorityCritical: "紧急",
  tlCatPreparation: "准备",
  tlCatMakeup: "化妆",
  tlCatHair: "发型",
  tlCatTeaCeremony: "敬茶",
  tlCatRom: "ROM",
  tlCatLunch: "午宴",
  tlCatRegistration: "签到",
  tlCatGrandEntrance: "进场",
  tlCatSpeech: "致辞",
  tlCatPerformance: "表演",
  tlCatCakeCutting: "切蛋糕",
  tlCatChampagne: "香槟塔",
  tlCatFirstMarchOut: "一出",
  tlCatSecondMarchIn: "二进",
  tlCatPhotoSession: "拍摄",
  tlCatSde: "SDE",
  tlCatLuckyDraw: "抽奖",
  tlCatDinner: "晚宴",
  tlCatAfterParty: "派对",
  tlCatOthers: "其他",
  tlSelectAll: "全选",
  tlShowArchived: "显示已归档",

  // Project 102 — Wedding Project Packages
  wpManager: "套餐管理",
  wpAddPackage: "添加套餐",
  wpEditPackage: "编辑套餐",
  wpSearch: "搜索套餐…",
  wpEmpty: "暂无套餐",
  wpEmptyHint: "添加婚礼项目套餐，管理项目与明细价值。",
  wpCreated: "套餐已创建",
  wpSaved: "套餐已保存",
  wpDeleted: "套餐已删除",
  wpDuplicated: "套餐已复制",
  wpArchived: "套餐已归档",
  wpName: "套餐名称",
  wpNameRequired: "请填写套餐名称",
  wpNotes: "备注",
  wpCurrency: "币种",
  wpItems: "明细项目",
  wpItemTitle: "项目名称",
  wpQty: "数量",
  wpUnitPrice: "单价",
  wpUnit: "单位",
  wpLineTotal: "小计",
  wpAddItem: "添加明细",
  wpRemoveItem: "移除",
  wpIncluded: "计入套餐价值",
  wpPackages: "套餐",
  wpPackageCount: "套餐数量",
  wpItemCount: "明细数量",
  wpTotalValue: "套餐总值",
  wpConfirmedValue: "已确认价值",
  wpSummaryHint: "项目套餐概览",
  wpShowArchived: "显示已归档",
  wpStatusDraft: "草稿",
  wpStatusConfirmed: "已确认",
  wpStatusCancelled: "已取消",
  wpStatusArchived: "已归档",
  wpNoPermission: "你没有权限查看套餐。",

  // Project 100 — Wedding Task Management
  taskManager: "任务管理",
  wtViewList: "列表",
  wtViewKanban: "看板",
  wtViewCalendar: "日历",
  wtViewProgress: "进度",
  wtAddTask: "新建任务",
  wtSearch: "搜索任务…",
  wtEmpty: "暂无任务",
  wtEmptyHint: "创建第一个任务，开始管理婚礼项目执行。",
  wtTaskCreated: "任务已创建",
  wtTaskSaved: "任务已保存",
  wtTaskDeleted: "任务已删除",
  wtTaskCompleted: "任务已完成",
  wtTaskDuplicated: "任务已复制",
  wtTaskArchived: "任务已归档",
  wtNoPermission: "你没有权限查看任务。",
  wtDueDate: "截止日期",
  wtStartDate: "开始日期",
  wtAssignee: "负责人",
  wtCoordinator: "统筹",
  wtPackage: "套餐",
  wtPriority: "优先级",
  wtReminder: "提醒",
  wtInternalNotes: "内部备注",
  wtAttachments: "附件",
  wtComments: "评论",
  wtActivityLog: "活动记录",
  wtAddComment: "添加评论",
  wtAddAttachment: "添加附件",
  wtAttachmentName: "附件名称",
  wtAttachmentUrl: "链接（可选）",
  wtComplete: "完成",
  wtDuplicate: "复制",
  wtArchive: "归档",
  wtRestore: "恢复",
  wtShowArchived: "显示已归档",
  wtBulkActions: "批量操作",
  wtSelectAll: "全选",
  wtSortBy: "排序",
  wtFilterStatus: "状态",
  wtFilterPriority: "优先级",
  wtAll: "全部",
  wtProgressLabel: "完成进度",
  wtOverdue: "已逾期",
  wtDueToday: "今日到期",
  wtUpcoming: "即将到期",
  wtNoDueDate: "无截止日期",
  wtStatusTodo: "待办",
  wtStatusInProgress: "进行中",
  wtStatusWaiting: "等待中",
  wtStatusCompleted: "已完成",
  wtStatusCancelled: "已取消",
  wtPriorityLow: "低",
  wtPriorityNormal: "普通",
  wtPriorityHigh: "高",
  wtPriorityUrgent: "紧急",
  wtSortSequence: "默认顺序",
  wtSortDueDate: "截止日期",
  wtSortPriority: "优先级",
  wtSortStatus: "状态",
  wtSortUpdated: "最近更新",
  wtSortTitle: "标题",
  wtCommentPlaceholder: "写下评论…",
  wtDaysLeft: (n: number) => (n === 0 ? "今天" : n > 0 ? `${n} 天后` : `逾期 ${Math.abs(n)} 天`),

  // Projects
  projects: "项目",
  operationalWorkFor: (business: string) => `${business} 的运营工作`,
  searchProjects: "搜索项目、客户预算…",
  noProjectsYet: "暂无项目",
  createProjectToOrganize: "创建项目以组织客户工作。",
  noMatchingProjects: "没有匹配的项目",
  projectName: "项目名称",
  projectNameRequired: "请填写项目名称",
  projectCreated: "项目已创建",
  projectUpdated: "项目已更新",
  projectProfile: "项目资料",
  newProjectTitle: "新建项目",
  editProject: "编辑项目",
  createProject: "创建项目",
  createProjectDesc: "开始新的合作。仅项目名称必填。",
  addProjectTo: (business: string) => `向 ${business} 添加项目。`,
  relatedClient: "关联客户",
  client: "客户",
  noClient: "无客户",
  startDate: "开始日期",
  endDate: "结束日期",
  projectType: "项目类型",
  planning: "策划中",
  projectActive: "进行中",
  completed: "已完成",
  archived: "已归档",
  optionalDescription: "可选描述",
  noPermissionProjects: "你没有权限查看项目。",
  projectActivitySoon: "项目动态将在后续更新中显示。",
  projectTasksSoon: "项目任务将在后续更新中显示。",
  meetingsMilestonesSoon: "会议与里程碑将在后续显示。",
  noCalendarEvents: "暂无日历事件",
  projectFilesSoon: "项目文件将在后续更新中显示。",
  noTeamMembersYet: "暂无团队成员",
  projectTeamSoon: "项目团队分配将在后续显示。",

  // Tasks
  tasks: "任务",
  searchTasks: "搜索任务…",
  noTasksYet: "暂无任务",
  createFirstTask: "创建第一个任务以开始跟进。",
  createTaskLinkProject: "创建任务并关联到项目。",
  noMatchingTasks: "没有匹配的任务",
  taskTitle: "任务标题",
  taskName: "任务名称",
  taskTitleRequired: "请填写任务标题",
  taskNameRequired: "请填写任务名称",
  taskCreated: "任务已创建",
  taskUpdated: "任务已更新",
  taskDetail: "任务详情",
  newTaskTitle: "新建任务",
  editTask: "编辑任务",
  createTask: "创建任务",
  createTaskDesc: "向项目添加工作。任务名称与项目为必填。",
  addTaskFor: (business: string) => `为 ${business} 添加任务。`,
  updateDetailsFor: (title: string) => `更新「${title}」的详细信息。`,
  dueDate: "截止日期",
  priority: "优先级",
  assignee: "执行人",
  relatedProject: "关联项目",
  selectProject: "选择项目",
  unassigned: "未分配",
  createProjectBeforeTasks: "请先创建项目再添加任务。",
  noAssignPermission: "你没有权限分配任务。",
  selectAProject: "请选择项目",
  todo: "待办",
  inProgress: "进行中",
  cancelled: "已取消",
  priorityLow: "低",
  priorityMedium: "中",
  priorityHigh: "高",
  priorityUrgent: "紧急",
  noPermissionTasks: "你没有权限查看任务。",
  taskActivitySoon: "任务动态将在后续更新中显示。",
  taskFilesSoon: "任务文件将在后续更新中显示。",
  taskCommentsSoon: "任务评论将在后续更新中显示。",
  taskHistorySoon: "任务变更历史将在后续显示。",
  taskWorkspace: "任务工作区",
  tasksFor: (business: string) => `${business} 的任务`,
  taskSingular: "任务",

  // Meetings
  meetings: "会议",
  noMeetingsYet: "暂无会议",
  createMeeting: "创建会议",
  meetingTitle: "会议标题",
  meetingCreated: "会议已创建",
  meetingUpdated: "会议已更新",

  // Files
  files: "文件",
  searchFiles: "搜索文件…",
  noFilesYet: "暂无文件",
  uploadFirstFile: "上传第一个文件以开始归档。",
  uploadFileLinkProject: "上传文件并关联到项目。",
  noMatchingFiles: "没有匹配的文件",
  uploadFile: "上传文件",
  uploadFileButton: "+ 上传文件",
  uploadFileDesc: "将文件附加到项目。支持 PDF、图片、视频、Word、Excel 和 ZIP。",
  fileName: "文件名",
  fileType: "文件类型",
  fileSize: "大小",
  uploadedAt: "上传时间",
  relatedProjectLabel: "关联项目",
  image: "图片",
  video: "视频",
  document: "文档",
  other: "其他",
  fileTypePdf: "PDF",
  fileTypeWord: "Word",
  fileTypeExcel: "Excel",
  fileTypeZip: "ZIP",
  loadingFiles: "正在加载文件…",
  loadingFile: "正在加载文件…",
  fileNotFound: "未找到文件",
  fileMissingOrSession: "该文件不存在，或是在其他浏览器会话中上传的。",
  backToFiles: "返回文件",
  previewUnavailable: "预览不可用",
  filePreviewSoon: "接入存储后将在此显示文件预览。",
  noVersionsYet: "暂无版本",
  versionHistorySoon: "版本历史将在后续更新中显示。",
  fileActivitySoon: "文件动态将在后续更新中显示。",
  openRelatedProject: "打开此文件所属的项目。",
  projectDocumentsFor: (business: string) => `${business} 的项目文档`,
  dropFilesHere: "将文件拖放到此处",
  orClickToBrowse: "或点击浏览 · 最大 50 MB",
  unsupportedType: "不支持的类型",
  fileUnsupportedType: (name: string) => `${name}：不支持的类型`,
  fileExceedsLimit: (name: string) => `${name}：超过 50 MB 限制`,
  projectNotFound: "未找到项目",
  chooseAtLeastOneFile: "请至少选择一个文件",
  uploadFailed: "上传失败",
  noFilesUploaded: "没有文件被上传",
  fileUploaded: "文件已上传",
  filesUploaded: (n: number) => `已上传 ${n} 个文件`,
  createProjectBeforeFiles: "请先创建项目再上传文件。",

  // Settings
  platformSettings: "平台设置",
  modularSettingsFor: (name: string) => `${name} 的模块化设置`,
  loadingSettings: "正在加载设置…",
  backToDashboard: "← 返回首页",
  backToDashboardPlain: "返回首页",
  account: "账户",
  organization: "组织",
  platform: "平台",
  preferences: "偏好设置",
  appearance: "外观",
  security: "安全",
  integrations: "集成",
  billing: "账单",
  related: "相关",
  manageWorkspacesLink: "管理工作区 →",
  manageCompaniesLink: "管理公司 →",
  userManagement: "用户管理（超级管理员）→",

  settingsProfileDesc: "你的账户身份与显示名称。",
  settingsPreferencesDesc: "语言、时区与通知偏好。",
  settingsNotificationsDesc: "选择接收哪些提醒。",
  settingsAppearanceDesc: "主题与显示选项。",
  settingsSecurityDesc: "密码与会话安全。",
  settingsCompanyDesc: "公司资料与运营设置。",
  settingsWorkspaceDesc: "工作区名称与区域设置。",
  settingsMembersDesc: "邀请与管理成员。",
  settingsIntegrationsDesc: "连接外部工具。",
  settingsBillingDesc: "订阅与付款。",

  // Notification Center (Project 076)
  notificationCenter: "通知中心",
  notificationCenterDesc: "跨模块的重要更新集中展示在这里。",
  notificationUnread: "未读",
  notificationRead: "已读",
  notificationMarkAllRead: "全部标为已读",
  notificationClearRead: "清除已读",
  notificationEmpty: "暂无通知",
  notificationEmptyDesc: "有新的任务、会议或客户动态时会显示在这里。",
  notificationStatusUnread: "未读",
  notificationStatusRead: "已读",
  notifTaskAssignedTitle: "任务已分配",
  notifTaskAssignedDesc: (title: string) => `你被分配了任务「${title}」`,
  notifTaskDueTodayTitle: "任务今日到期",
  notifTaskDueTodayDesc: (title: string) => `任务「${title}」今日到期`,
  notifTaskOverdueTitle: "任务已逾期",
  notifTaskOverdueDesc: (title: string) => `任务「${title}」已逾期`,
  notifMeetingReminderTitle: "会议提醒",
  notifMeetingReminderDesc: (title: string) => `会议「${title}」即将开始`,
  notifMeetingUpdatedTitle: "会议已更新",
  notifMeetingUpdatedDesc: (title: string) => `会议「${title}」信息已更新`,
  notifClientCreatedTitle: "客户已创建",
  notifClientCreatedDesc: (name: string) => `新客户「${name}」已加入`,
  notifVendorAssignedTitle: "供应商已关联",
  notifVendorAssignedDesc: (name: string) => `供应商「${name}」已关联到工作`,
  notifProjectUpdatedTitle: "项目已更新",
  notifProjectUpdatedDesc: (name: string) => `项目「${name}」有新的更新`,
  notifInvoicePlaceholderTitle: "发票（即将推出）",
  notifDocumentsPlaceholderTitle: "文档（即将推出）",
  notifCalendarPlaceholderTitle: "日历（即将推出）",
  notifPlaceholderDesc: "此通知类型已预留，投递能力即将接入。",

  // Search / Command Palette (Project 075)
  universalSearch: "命令面板",
  commandPalette: "命令面板",
  searchPlaceholder: "搜索客户、项目、任务…",
  searchAnything: "搜索或输入命令…",
  searchDialogDescription:
    "搜索客户、项目、供应商、会议、任务，或运行快捷操作与导航。",
  noResults: "无结果",
  tryDifferentQuery: "尝试其他关键词。",
  recentSearches: "最近搜索",
  recent: "最近",
  recentItems: "最近打开",
  noRecentItems: "暂无最近打开的记录",
  commands: "快捷操作",
  navigation: "导航",
  futureModules: "即将推出",
  noCommandsAvailable: "暂无可用命令",
  itemCount: (n: number) => `${n} 项`,

  // Empty / generic module
  comingSoon: "即将推出",
  moduleNotAvailable: "此模块尚未开放。",
  noDataYet: "暂无数据",
  nothingInDatabase: "数据库中尚无记录。添加后会显示在这里。",

  // User management (Settings → Users)
  userManagementTitle: "用户管理",
  userManagementDesc: "仅限邀请访问。只有超级管理员可以邀请用户。",
  inviteUser: "邀请用户",
  inviteUserDesc:
    "发送安全邀请。用户打开链接后设置密码。邀请 72 小时后过期，且仅可使用一次。",
  usersSection: "用户",
  usersSectionDesc: "已接受邀请的账户。",
  noUsersYet: "暂无用户。邀请他人以开始使用。",
  invitationsSection: "邀请",
  invitationsSectionDesc: "跟踪待处理、已接受与已过期的邀请。",
  noInvitationsYet: "暂无邀请。",
  fullName: "姓名",
  joined: "加入时间",
  expires: "过期时间",
  resend: "重新发送",
  sending: "发送中…",
  sendInvitation: "发送邀请",
  invitationSentTo: (email: string) => `邀请已发送至 ${email}`,
  invitationCreated: "邀请已创建",
  inviteLinkCopyNow: "邀请链接（请立即复制）",
  invitationCancelled: "邀请已取消",
  inviteStatusPending: "待处理",
  inviteStatusAccepted: "已接受",
  inviteStatusExpired: "已过期",
  inviteStatusRevoked: "已取消",
  fullNameRequired: "请填写姓名",
  companyRequired: "请填写公司",
  roleAdmin: "管理员",
  roleCoordinator: "统筹",
  roleEventPlanner: "活动策划",
  roleFinance: "财务",
  roleSales: "销售",
  roleDesigner: "设计师",
  roleStaff: "员工",

  // Module placeholder pages
  openWorkspace: "打开工作区",
  openPreviewWorkspace: "打开预览工作区",
  orOpen: "或打开",
  timelinePageTitle: "时间线",
  timelinePageDesc: "跨会议、任务与动态的统一时间流。",
  timelineWorkspaceTitle: "时间线工作区",
  timelineWorkspaceEmptyDesc: "打开时间线工作区浏览按时间排序的事件。",
  openTimelineWorkspace: "打开时间线工作区",
  notificationsPageTitle: "通知",
  notificationsPageDesc: "通知工作区基础已就绪。投递服务商稍后接入。",
  notificationWorkspaceTitle: "通知工作区",
  notificationWorkspaceEmptyDesc:
    "打开通知工作区预览，浏览收件箱、定时项与模板。",
  openNotificationWorkspaceBtn: "打开通知工作区",
  financePageTitle: "财务",
  financePageDesc: "财务工作区基础已就绪。持久化与支付稍后接入。",
  financeWorkspaceTitle: "财务工作区",
  financeWorkspaceEmptyDesc:
    "打开财务工作区预览，浏览交易、发票、报价与预算。",
  openFinanceWorkspace: "打开财务工作区",
  automationsPageTitle: "自动化",
  automationsPageDesc: "自动化工作区基础已就绪。执行引擎稍后接入。",
  automationWorkspaceTitle: "自动化工作区",
  automationWorkspaceEmptyDesc:
    "打开自动化工作区预览，探索工作流、触发器、条件与动作。",
  openAutomationWorkspace: "打开自动化工作区",
  documentsPageTitle: "文档",
  documentsPageDesc: "文档工作区基础已就绪。存储与上传稍后接入。",
  documentWorkspaceTitle: "文档工作区",
  documentWorkspaceEmptyDesc:
    "打开文档工作区预览，浏览文档、文件夹、版本与动态。",
  openDocumentWorkspace: "打开文档工作区",
  somethingWentWrong: "出了点问题",
  unexpectedError: "发生意外错误，请重试。",
  tryAgain: "重试",

  // Search groups / commands
  searchGroupCommands: "快捷操作",
  searchGroupClients: "客户",
  searchGroupProjects: "项目",
  searchGroupTasks: "任务",
  searchGroupFiles: "文档",
  searchGroupCalendar: "日历",
  searchGroupMeetings: "会议",
  searchGroupVendors: "供应商",
  searchGroupTeamMembers: "团队成员",
  searchGroupSettings: "设置",
  searchGroupWorkspace: "导航",
  searchGroupTimeline: "时间线",
  searchGroupFinance: "财务",
  searchGroupNotifications: "通知",
  searchGroupAutomation: "自动化",
  searchGroupCompany: "公司",
  cmdCreateClient: "新建客户",
  cmdCreateClientDesc: "打开新建客户页",
  cmdCreateVendor: "新建供应商",
  cmdCreateVendorDesc: "打开新建供应商页",
  cmdCreateProject: "新建项目",
  cmdCreateProjectDesc: "打开新建项目页",
  cmdCreateMeeting: "新建会议",
  cmdCreateMeetingDesc: "打开新建会议页",
  cmdCreateTask: "新建任务",
  cmdCreateTaskDesc: "打开新建任务页",
  cmdUploadFile: "上传文件",
  cmdUploadFileDesc: "将文件附加到项目",
  cmdInviteMember: "邀请成员",
  cmdInviteMemberDesc: "邀请他人加入工作区",
  cmdOpenSettings: "打开设置",
  cmdOpenSettingsDesc: "工作区与账户设置",
  navGoHome: "首页",
  navGoClients: "客户",
  navGoProjects: "项目",
  navGoVendors: "供应商",
  navGoMeetings: "会议",
  navGoTasks: "任务",
  navGoSettings: "设置",
  navGoDocuments: "文档",
  navGoFinance: "财务",
  navGoCalendar: "日历",
  placeholderModuleDesc: "模块即将推出",

  // Workspace tabs (extra)
  checklist: "清单",
  transactions: "交易",
  invoices: "发票",
  quotations: "报价",
  budget: "预算",
  folders: "文件夹",
  versions: "版本",
  workflow: "工作流",
  trigger: "触发器",
  conditions: "条件",
  actionSteps: "动作",
  tabScheduled: "定时",
  templates: "模板",
  past: "过去",
  logs: "日志",
  calendarComingSoon: "日历（即将推出）",
  historyComingSoon: "历史（即将推出）",
  logsComingSoon: "日志（即将推出）",

  // Shell leftovers
  openNavigation: "打开导航",
  workspaceSections: "工作区分区",
  linkedProjectTitle: "关联项目",
  linkedProjectAssociated: "与此记录关联的项目",
  noProjectLinkedTitle: "未关联项目",
  linkProjectFromEdit: "在「编辑详情」中关联项目后，即可在此查看。",
  projectStatusPlanning: "策划中",
  projectStatusActive: "进行中",
  projectStatusCompleted: "已完成",
  projectStatusArchived: "已归档",
  projectStatusInquiry: "询盘",
  projectStatusProposal: "方案",
  projectStatusConfirmed: "已确认",
  projectStatusExecution: "执行中",
  projectStatusCancelled: "已取消",
  aiTellRiva: "告诉 RIVA…",
  aiPlaceholderExample:
    "例如：提醒我明天跟进 Jason / 建立婚礼时间线 / 回复客户 / 生成报价单",
  aiSend: "发送",
  loadingEllipsis: "加载中…",

  // Shared status / labels
  unknown: "未知",
  waiting: "等待中",
  draft: "草稿",
  sent: "已发送",
  paid: "已付款",
  voidStatus: "作废",
  enabled: "已启用",
  disabled: "已停用",
  yes: "是",
  no: "否",
  unread: "未读",
  delivered: "已送达",
  queued: "排队中",
  reminder: "提醒",
  announcement: "公告",
  channelInAppShort: "应用内",
  channelSms: "短信",
  channelWhatsapp: "WhatsApp",
  channelPush: "推送",
  allTypes: "全部类型",
  allStatuses: "全部状态",
  allChannels: "全部渠道",
  spreadsheet: "表格",
  audio: "音频",
  folder: "文件夹",
  total: "合计",
  tax: "税费",
  revenue: "收入",
  expense: "支出",
  profit: "利润",
  cashIn: "现金流入",
  cashOut: "现金流出",
  netCashFlow: "净现金流",
  totalIncome: "总收入",
  totalExpenses: "总支出",
  outstandingInvoices: "未结发票",
  outstandingPaymentsLabel: "待收款",
  actual: "实际",
  remaining: "剩余",
  totalDocuments: "文档总数",
  totalStorage: "存储总量",
  linkedWorkspace: "关联工作区",
  totalNotifications: "通知总数",
  taskActivity: "任务动态",
  futureEvents: "未来事件",
  placeholderValue: "占位",
  workflowName: "工作流名称",
  triggerSummary: "触发器摘要",
  conditionsSummary: "条件摘要",
  actionsSummary: "动作摘要",
  lastModified: "最后修改",
  relatedProjectTitle: "关联项目",
  noConditions: "无条件",
  noActions: "无动作",
  noDescription: "暂无描述。",
  delayStep: "延迟步骤",
  sendNotification: "发送通知",
  createDocumentAction: "创建文档",
  webhookPlaceholder: "Webhook 占位",
  updateTaskAction: "更新任务",
  updateProjectAction: "更新项目",
  assignUserAction: "分配用户",
  searchDocuments: "搜索文档…",
  searchNotifications: "搜索通知…",
  invoiceFallback: "发票",
  quotationFallback: "报价",
  readStatus: "已读",

  // Workspace eyebrows / empty states
  clientWorkspace: "客户工作区",
  projectWorkspaceTitle: "项目工作区",
  taskWorkspaceEyebrow: "任务工作区",
  documentWorkspaceEyebrow: "文档工作区",
  financeWorkspaceEyebrow: "财务工作区",
  notificationWorkspaceEyebrow: "通知工作区",
  timelineWorkspaceEyebrow: "时间线工作区",
  automationWorkspaceEyebrow: "自动化工作区",
  timelineEmpty: "时间线为空",
  timelineEmptyDesc: "创建任务或打开会议以填充此动态。",
  calendarPlaceholderDesc: "日历视图为后续版本占位。",
  nothingUpcoming: "暂无即将到来的事项",
  nothingUpcomingDesc: "未来的任务与会议将显示在这里。",
  noPastItems: "暂无历史事项",
  noPastItemsDesc: "完成后的历史将随时间出现在这里。",
  noTimelineItemsYet: "暂无时间线事项",
  noTimelineItemsDesc: "任务、会议与动态创建后会显示在这里。",
  automationHistoryDesc: "执行引擎就绪后，自动化运行历史将显示在这里。",
  automationLogsDesc: "工作者与日志就绪后，执行日志将显示在这里。",
  checklistSoonDesc: "清单持久化就绪后，任务清单将显示在这里。",
  attachmentsSoonDesc: "存储就绪后，任务文件将显示在这里。",
  projectTimelineSoon: "项目时间线与里程碑将显示在这里。",
  projectDocumentsSoon: "项目文件与文档将显示在这里。",
  projectFinanceSoon: "项目发票与付款将显示在这里。",
  projectTasksSoonPlaceholder: "项目任务与分配将显示在这里。",
  projectActivitySoonPlaceholder: "项目动态与审计历史将显示在这里。",
  clientDocumentsSoon: "接入文档持久化后，客户文档将显示在这里。",
  clientTimelineSoon: "按客户筛选时间线后，事件将显示在这里。",
  clientFinanceSoon: "此客户的报价、发票与付款将显示在这里。",
  linkClientToProjectHint:
    "在「编辑详情」中将此客户关联到项目后，即可在此查看。",
  noClientsLinked: "未关联客户",
  noClientsLinkedDesc: "将客户关联到此项目，以便集中管理交付联系人。",
  clientsUnavailable: "客户不可用",
  clientsUnavailableDesc: "你没有权限查看此项目的客户。",
  noVendorsLinked: "未关联供应商",
  noVendorsLinkedDesc: "将供应商分配到此项目以便协调交付。",
  vendorsUnavailable: "供应商不可用",
  vendorsUnavailableDesc: "你没有权限查看此项目的供应商。",
  addVendor: "添加供应商",
  addClient: "添加客户",
  activate: "激活",
  projectActivated: "项目已激活",
  projectArchivedToast: "项目已归档",
  projectArchivedCannotEdit: "项目已归档，请先恢复后再编辑。",
  projectDeletedToast: "项目已删除",
  projectRestoredToast: "项目已恢复",
  markedForFollowUp: "已标记跟进",
  clientArchivedToast: "客户已归档",
  clientRestoredToast: "客户已恢复",
  corporateClient: "企业客户",
  individualClient: "个人客户",
  bride: "新娘",
  groom: "新郎",
  noClientsYetTitle: "暂无客户",
  addClientsForCompany: "为此公司添加新娘、新郎、企业或个人客户。",
  noProjectsYetTitle: "暂无项目",
  createProjectOrganize: "创建项目以组织此公司的客户与供应商。",
  ownerAssigned: "已指定负责人",
  assigneeAssigned: "已指定执行人",
  ownerRemoved: "已移除负责人",
  assigneeRemoved: "已移除执行人",
  taskDeleted: "任务已删除",
  taskCompletedToast: "任务已完成",
  taskRestoredToast: "任务已恢复",
  taskArchivedToast: "任务已归档",
  completedDate: "完成日期",
  followers: "关注者",
  tags: "标签",
  openMeeting: "打开会议",
  commaSeparatedTags: "用逗号分隔的标签",
  meetingIdOptional: "会议 ID（可选）",
  newTaskBtn: "新建任务",

  // Dashboard legacy
  commandCenter: "指挥中心",
  todayOverview: "今日概览",
  todaysWeddings: "今日婚礼",
  followUpClients: "待跟进客户",
  monthlyRevenue: "本月营业额",
  monthlyProfit: "本月利润",
  outstandingPaymentsDash: "待收款",
  upcomingWeddings: "最近婚礼",
  weddingName: "婚礼名称",
  venue: "场地",
  dueTime: "截止时间",
  addWedding: "新增婚礼",
  addQuote: "新增报价",
  signIn: "登录",
  weddingStatusInquiry: "询价",
  myTasks: "我的任务",
  openUpcomingWork: "进行中与即将到期的工作",
  allTasksArrow: "全部任务 →",
  noOpenTasksYet: "暂无进行中的任务。",
  openTaskWorkspaceArrow: "打开任务工作区 →",
  recentActivityTitle: "最近动态",
  latestTaskActivity: "公司最近的任务动态",
  timelineArrow: "时间线 →",
  activityRequiresTaskAccess: "动态预览需要任务访问权限。",
  todaysSchedule: "今日日程",
  meetingsAndDueWork: "今日的会议与到期工作",
  nothingScheduledToday: "今日暂无安排。",
  companyOverview: "公司概览",
  companySettingsArrow: "公司设置 →",
  upcomingMeetingsTitle: "即将到来的会议",
  companySchedule: "公司日程",
  meetingsArrow: "会议 →",
  inboxPreview: "收件箱预览",
  unreadPreviewItems: (n: number) => `${n} 条未读预览`,
  inboxArrow: "收件箱 →",
  noNotificationsPreview: "暂无通知可预览。",
  quickActionsJump: "跳转到常用工作区",
  noShortcutsAvailable: "暂无快捷入口。",
  teamFallback: "团队",
  waitMinutes: (n: string | number) => `等待 ${n} 分钟`,
  templateLabel: (t: string) => `模板 ${t}`,
  channelLabel: (c: string) => `渠道 ${c}`,
  createTaskNamed: (title: string) => `创建任务「${title}」`,
  createMeetingNamed: (title: string) => `创建会议「${title}」`,
  createDocumentNamed: (name: string) => `创建文档「${name}」`,
  webhookWithUrl: (url: string) => `Webhook 占位 · ${url}`,
  actionsSequenceDesc: "动作序列预览 — 延迟、通知、创建步骤、Webhook 占位",
  noActionsConfigured: "尚未配置动作。",
  reportsPreviewDesc: "仅预览合计 — 图表与导出稍后推出",
  meetingSingular: "会议",
  vendorSingular: "供应商",
  amount: "金额",
  followUpDate: "跟进日期",
  manageClientsLink: "管理客户 →",
  workflowPreviewDesc: "工作流信息 — 启用/停用仅为预览",
  noConditionsConfigured: "尚未配置条件。",
  triggerType: "触发器类型",
  noExtraConfig: "无额外配置。",
  manualTriggerPreview: "手动触发预览",
  workflowOverview: "工作流概览",
  financeSummary: "财务摘要",
  budgetSummary: "预算摘要",
  cashFlowSummary: "现金流摘要",
  cashInVsOut: "现金流入与流出",
  recentActivityTitle2: "最近动态",
  librarySummary: "资料库摘要",
  recentUploads: "最近上传",
  channelSummary: "渠道摘要",
  optionalProjectAssociation: "此客户的可选项目关联",
  meetingsLinkedToClient: "与此客户关联的会议",
  auditTrailClient: "客户变更的审计记录（会话缓冲）",
  updateNotesFromEditDetails: "请在「编辑详情」中更新备注。",
  clientTypeBride: "新娘",
  clientTypeGroom: "新郎",
  clientTypeIndividual: "个人",
  relatedMeetingsTitle: "相关会议",
  workspaceSummary: "工作区摘要",
  recentTasks: "最近任务",
  relationships: "关联",
  assignment: "分配",
  selectATask: "选择任务",
  updateAndSave: "更新并保存更改",
  noUploadsYet: "暂无上传。",
  noFoldersYet: "暂无文件夹。",
  folderEmpty: "此文件夹为空。",
  noDocumentsMatch: "没有匹配的文档。",
  updatedBy: "更新人",
  noVersionHistoryYet: "暂无版本历史。",
  noNotificationsMatch: "没有匹配的通知。",
  channel: "渠道",
  recipient: "接收人",
  nothingScheduled: "暂无定时项。",
  scheduledTime: "定时时间",
  noTemplatesDefined: "尚未定义模板。",
  noChannelActivity: "暂无渠道动态。",
  timelineSummary: "时间线摘要",
  recentLabel: "最近",
  noInvoicesYet: "暂无发票。",
  overallProgress: "总体进度",
  noBudgetLinesYet: "暂无预算行。",
  noTransactionsYet: "暂无交易。",
  noQuotationsYet: "暂无报价。",
  searchQuotations: "搜索报价编号或客户…",
  noMatchingQuotations: "没有匹配的报价",
  addFirstQuotation: "创建第一份报价以开始。",
  quotationNumber: "报价编号",
  quotationNumberAuto: "保存时自动生成",
  previousPage: "上一页",
  nextPage: "下一页",
  pageOf: (page: number, totalPages: number) =>
    `第 ${page} / ${totalPages} 页`,
  createQuotation: "创建报价",
  quotationCreated: "报价已创建",
  quotationUpdated: "报价已更新",
  companyInformation: "公司信息",
  companyInformationHint: "来自公司设置，生成文档时自动带入。",
  registrationNo: "注册编号",
  bankName: "银行名称",
  bankAccountName: "银行账户名",
  bankAccountNumber: "银行账号",
  billToSection: "账单对象",
  billToName: "账单名称",
  billToAddress: "账单地址",
  billToRegistration: "客户注册编号",
  attentionTo: "经办人 / Attn",
  eventInformation: "活动信息",
  eventTitle: "活动标题",
  eventDate: "活动日期",
  eventVenue: "场地",
  eventLocation: "地点",
  eventNotes: "活动备注",
  discount: "折扣",
  subtotal: "小计",
  grandTotal: "总计",
  quotationMetadata: "报价元数据",
  yourReference: "对方参考号",
  preparedBy: "编制人",
  ccLabel: "抄送",
  issueDate: "开具日期",
  packageLibrary: "套餐库",
  packageLibraryHint: "选择套餐后自动填入明细行，可继续手动调整。",
  selectPackage: "选择套餐…",
  additionalCharges: "附加费用 / 折扣",
  additionalChargesHint: "折扣行请填写金额；保存时会记入折扣字段。",
  notesAndTerms: "备注与条款",
  validityLabel: "有效期说明",
  deliveryTerm: "交付条款",
  paymentTerms: "付款条款",
  termsAndConditions: "条款与条件",
  bankDetails: "银行信息",
  documentFooter: "页脚",
  salesPerson: "销售负责人",
  internalReference: "内部参考号",
  corporateMode: "企业客户",
  weddingMode: "婚礼客户",
  shippingAddress: "收货地址",
  brideName: "新娘姓名",
  groomName: "新郎姓名",
  coupleDisplayName: "新人显示名",
  eventInformationRequired: "活动信息为必填，将用于报价与后续合同/活动单。",
  eventCategory: "活动类型",
  venueAddress: "场地地址",
  mapLink: "地图链接",
  eventDay: "活动星期",
  startTime: "开始时间",
  endTime: "结束时间",
  guestCount: "宾客人数",
  dressCode: "着装要求",
  parkingNotes: "停车备注",
  loadingBayNotes: "卸货区备注",
  addPackage: "+ 添加套餐",
  addCharge: "+ 添加附加费用",
  noLineItemsYet: "暂无明细行。",
  item: "项目",
  moveUp: "上移",
  moveDown: "下移",
  duplicate: "复制",
  unit: "单位",
  lineNotes: "行备注",
  lineNotesPlaceholder: "显示在该明细下方的说明…",
  pricingSummary: "价格汇总",
  packageDiscount: "套餐折扣",
  manualDiscount: "手动折扣",
  depositPercent: "定金比例 %",
  depositAmount: "定金金额",
  deposit: "定金",
  balanceDue: "尾款",
  eventNotesPlaceholder:
    "例：客户需提供工作人员餐食；加时每 30 分钟每位乐手 RM500…",
  eventTitleRequired: "请填写活动标题。",
  paymentDetails: "付款详情",
  paymentDetailsHint: "默认来自公司设置，可按本报价调整。",
  paymentReference: "付款参考号",
  internalNotesHint: "仅内部可见，不会打印到 PDF。",
  attachmentsHint: "场地平面图、情绪板、时间表等（URL）。",
  attachmentName: "附件名称",
  attachmentUrl: "附件链接",
  addAttachment: "+ 添加附件",
  removeAttachment: "移除附件",
  generatePdf: "生成 PDF",
  emailClient: "邮件发给客户",
  whatsappClient: "WhatsApp 发给客户",
  duplicateQuotation: "复制报价",
  convertToContract: "转为合同",
  convertToBooking: "转为预订确认",
  comingSoonAction: "即将推出",
  swiftCode: "SWIFT 代码",
  signatureUrl: "签名图片 URL",
  previewDocument: "预览文档",
  downloadDocument: "下载 PDF",
  regenerateDocument: "重新生成",
  documentReady: "文档已准备好",
  documentRegenerated: "文档已重新生成",
  documentPreview: "文档预览",
  quotationDocument: "报价文档",
  documentPreviewFailed: "无法预览文档。",
  openPdf: "打开 PDF",
  backToQuotation: "← 报价详情",
  editQuotation: "编辑报价",
  quotationDetail: "报价详情",
  referenceNumber: "编号",
  validUntil: "有效期至",
  lineItems: "明细行",
  addLineItem: "添加行",
  removeLineItem: "移除",
  quantity: "数量",
  unitPrice: "单价",
  quotationNotes: "备注",
  sendQuotation: "发送报价",
  acceptQuotation: "接受",
  rejectQuotation: "拒绝",
  expireQuotation: "标记过期",
  voidQuotation: "作废",
  convertToInvoice: "转为发票",
  backToQuotations: "← 报价列表",
  lineDescriptionRequired: "请填写明细描述",
  atLeastOneLineItem: "至少需要一行明细",
  noUpcomingMeetings: "暂无即将到来的会议。",
  comingSoonTitle: "即将推出",
  thisFolderEmpty: "此文件夹为空。",
  relatedEntities: "关联实体",
  projectSingular: "项目",

  // Workspace panel copy (finance / document / notification / automation)
  triggerConfigDesc: "触发器类型与配置 — 尚未执行",
  triggerConfiguration: "触发器配置",
  runNowUnavailable: "执行引擎上线前无法立即运行。",
  runManuallySoon: "手动运行（即将推出）",
  conditionsListDesc: "条件列表，支持「且 / 或」分组 — 仅预览",
  valueLabel: "值",
  toLabel: "至",
  andMode: "且",
  orMode: "或",
  conditionCountSummary: (n: number, mode: string) =>
    `${n} 个条件（${mode}）`,
  actionCountSummary: (n: number) => `${n} 个动作`,
  automationPreviewSummary: "来自自动化域的预览摘要",
  openWorkflow: "打开工作流",
  workflowType: "工作流",
  versionHistoryDesc: "只读版本历史 — 恢复与上传稍后推出",
  folderBrowserDesc: "简易文件夹浏览 — 暂不支持拖放",
  documentsPanelDesc: "搜索、排序并按类型筛选 — 文档域预览数据",
  browseDocuments: "浏览文档",
  libraryTotalsDesc: "此预览的合计与关联工作区",
  newestDocumentsDesc: "按创建日期排序的最新文档",
  latestDocumentHistory: "最新文档历史预览",
  viewActivity: "查看动态",
  documentHistoryDesc: "文档历史 — 最新在前",
  financeHistoryDesc: "财务历史 — 最新在前",
  quotationsStatusHint: "草稿 · 已发送 · 已接受 · 已拒绝 · 已过期",
  issuedAtLabel: (date: string) => `开具于 ${date}`,
  invoicesStatusHint: "草稿 · 已发送 · 已付款 · 已逾期 · 已取消",
  budgetProgressHint: "预算 · 实际 · 剩余 · 进度",
  budgetAmountLabel: (v: string) => `预算 ${v}`,
  actualAmountLabel: (v: string) => `实际 ${v}`,
  remainingAmountLabel: (v: string) => `剩余 ${v}`,
  allFinanceRecords: "此工作区的全部财务记录",
  financeTotalsDesc: "来自财务域预览记录的合计",
  viewTransactions: "查看交易",
  budgetPlannedVsActual: "各预算行的计划与实际支出",
  latestFinanceHistory: "最新财务历史预览",
  notificationSummaryTitle: "通知摘要",
  notificationTotalsDesc: "来自通知域预览记录的合计",
  openInbox: "打开收件箱",
  channelCountsDesc: "按投递渠道统计（预览）",
  latestNotificationHistory: "最新通知历史预览",
  inboxPanelDesc: "搜索、筛选、排序与标记已读 — 仅本地预览",
  markUnread: "标为未读",
  markRead: "标为已读",
  sentAt: "发送时间",
  scheduledPanelDesc: "排队与待发送通知 — 尚无后台任务",
  templatesPanelDesc: "来自通知域的只读通知模板",
  priorityWithValue: (p: string) => `优先级 ${p}`,
  notificationHistoryDesc: "通知历史 — 最新在前",
  updatedAtCol: "更新时间",
  versionCol: "版本",
  progress: "进度",
  refund: "退款",
  paymentType: "付款",
  dismissed: "已忽略",
  docStatusReady: "就绪",
  docStatusPublished: "已发布",
  categoryServices: "服务",
  categoryVenue: "场地",
  categoryMaterials: "物料",
  categoryMarketing: "营销",
  categoryFees: "费用",
  categoryGeneral: "常规",
  categoryProducts: "产品",
  previewChenWedding: "陈氏婚礼",
  previewGrandBallroom: "大宴会厅",

  // Project 077 — Timeline Engine
  expand: "展开",
  collapse: "收起",
  timelineProgress: "项目进度",
  timelineProgressDetail: (completed: number, total: number) =>
    `已完成 ${completed} / ${total} 个里程碑`,
  relatedTasks: "相关任务",
  noRelatedTasks: "暂无关联任务",
  milestoneInquiry: "咨询意向",
  milestoneInquiryDesc: "客户初次询价与需求收集。",
  milestoneConsultation: "咨询洽谈",
  milestoneConsultationDesc: "深度沟通方案、预算与期望。",
  milestoneBooking: "预订确认",
  milestoneBookingDesc: "确认档期并完成预订。",
  milestonePlanning: "策划筹备",
  milestonePlanningDesc: "整体策划与执行计划落地。",
  milestoneVendorConfirmation: "供应商确认",
  milestoneVendorConfirmationDesc: "确认供应商档期与交付细节。",
  milestoneFinalMeeting: "最终会议",
  milestoneFinalMeetingDesc: "婚礼前最终确认与彩排安排。",
  milestoneWeddingDay: "婚礼当日",
  milestoneWeddingDayDesc: "活动执行与现场交付。",
  milestoneCompletion: "项目完成",
  milestoneCompletionDesc: "收尾、复盘与归档。",
  milestoneStatusPending: "待开始",
  milestoneStatusActive: "进行中",
  milestoneStatusCompleted: "已完成",
  milestoneStatusSkipped: "已跳过",
  projectTimelineTitle: "执行时间线",
  projectTimelineDesc: "项目生命周期里程碑 — 非日历视图。",

  // Project 078 — Calendar Engine
  calendarEngineDesc: "会议、任务与里程碑的可视化日程 — 不另建日历记录。",
  calendarViewMonth: "月",
  calendarViewWeek: "周",
  calendarViewDay: "日",
  calendarViewAgenda: "议程",
  calendarAgendaSoon: "议程视图即将推出。",
  calendarTypeMeeting: "会议",
  calendarTypeTask: "任务",
  calendarTypeMilestone: "里程碑",
  calendarPrev: "上一段",
  calendarNext: "下一段",
  calendarToday: "今天",
  calendarJump: "跳转到日期",
  noPermissionCalendar: "你没有权限查看日历数据源。",

  // Project 079 — Activity Feed Engine
  activityFeed: "动态流",
  activityFeedTitle: "活动动态",
  activityFeedDesc: "跨模块统一事件流 — 最新在前。",
  activityGroupToday: "今天",
  activityGroupYesterday: "昨天",
  activityGroupEarlier: "更早",
  activityTypeCreated: "创建",
  activityTypeUpdated: "更新",
  activityTypeAssigned: "分配",
  activityTypeCompleted: "完成",
  activityTypeCancelled: "取消",
  activityTypeScheduled: "安排",
  activityTypeStatusChanged: "状态变更",
  activityTypeReminder: "提醒",
  activityTypePublished: "发布",
  activityTypePlaceholder: "占位",
  activityStatusLine: (status: string) => `状态：${status}`,
  activityProjectCreated: (name: string) => `项目已创建：${name}`,
  activityProjectUpdated: (name: string) => `项目已更新：${name}`,
  activityClientCreated: (name: string) => `客户已创建：${name}`,
  activityClientUpdated: (name: string) => `客户已更新：${name}`,
  activityVendorCreated: (name: string) => `供应商已创建：${name}`,
  activityVendorUpdated: (name: string) => `供应商已更新：${name}`,
  activityMeetingScheduled: (title: string) => `会议已安排：${title}`,
  activityMeetingUpdated: (title: string) => `会议已更新：${title}`,
  activityTaskCreated: (title: string) => `任务已创建：${title}`,
  activityTaskUpdated: (title: string) => `任务已更新：${title}`,
  activityTaskAssigned: (title: string) => `任务已分配：${title}`,
  activityTaskCompleted: (title: string) => `任务已完成：${title}`,
  activityMilestoneCompleted: (milestone: string, project: string) =>
    `里程碑完成：${milestone}（${project}）`,
  activityMilestoneActive: (milestone: string, project: string) =>
    `里程碑进行中：${milestone}（${project}）`,
  activityFinancePlaceholder: "财务动态（即将推出）",
  activityDocumentsPlaceholder: "文档动态（即将推出）",
  activityCalendarPlaceholder: "日历动态（即将推出）",
  noPermissionActivity: "你没有权限查看活动数据源。",
} as const;

export type UiZhKey = keyof typeof uiZh;
