export type {
  Client,
  ClientStatus,
  ClientType,
  Company,
  CompanyStatus,
  CompanyType,
  CoreInvitation,
  CoreInvitationStatus,
  CorePermission,
  CoreRole,
  Meeting,
  MeetingParticipant,
  MeetingStatus,
  MeetingType,
  Membership,
  MembershipRole,
  MembershipStatus,
  Person,
  PersonRole,
  PersonStatus,
  Project,
  ProjectStatus,
  ProjectType,
  SessionContext,
  Vendor,
  VendorCategory,
  VendorStatus,
  Workspace,
  WorkspaceContext,
  WorkspaceMember,
  WorkspaceStatus,
} from "@/core/types";

export {
  ACTIVE_COMPANY_COOKIE,
  listCompaniesForUserInWorkspace,
  resolveActiveCompany,
  switchActiveCompany,
} from "@/core/company/active-company";

export {
  createCompany,
  getCompanyById,
  getCompanyBySlug,
  listCompaniesByWorkspace,
  updateCompanySettings,
} from "@/core/company/company";

export {
  archiveClient,
  createClient,
  getClientById,
  listClientsByCompany,
  listClientsByProject,
  markClientFollowUp,
  restoreClient,
  updateClient,
} from "@/core/client/client";

export {
  listClientAuditTrail,
  recordClientAudit,
} from "@/core/client/audit";

export {
  activateProject,
  archiveProject,
  createProject,
  deleteProject,
  getProjectById,
  listProjectsByClient,
  listProjectsByCompany,
  listProjectsByWorkspace,
  restoreProject,
  updateProject,
} from "@/core/project/project";

export {
  archiveVendor,
  createVendor,
  deactivateVendor,
  getVendorById,
  listVendorsByCompany,
  listVendorsByProject,
  restoreVendor,
  updateVendor,
} from "@/core/vendor/vendor";

export {
  listVendorAuditTrail,
  recordVendorAudit,
} from "@/core/vendor/audit";

export {
  cancelMeeting,
  completeMeeting,
  createMeeting,
  getMeetingById,
  listMeetingsByClient,
  listMeetingsByCompany,
  listMeetingsByProject,
  listMeetingsByVendor,
  updateMeeting,
} from "@/core/meeting/meeting";

export {
  listMeetingAuditTrail,
  recordMeetingAudit,
} from "@/core/meeting/audit";

export {
  CORE_PERMISSIONS,
  CORE_ROLES,
  CLIENT_SOURCES,
  CLIENT_STATUSES,
  CLIENT_TYPES,
  COMPANY_STATUSES,
  COMPANY_TYPES,
  MEETING_STATUSES,
  MEETING_TYPES,
  MEMBERSHIP_ROLES,
  MEMBERSHIP_STATUSES,
  PERSON_STATUSES,
  PROJECT_STATUSES,
  PROJECT_TYPES,
  VENDOR_CATEGORIES,
  VENDOR_STATUSES,
  WEDDING_SESSIONS,
  WORKSPACE_STATUSES,
} from "@/core/types";

export type {
  AssignTaskInput,
  CreateTaskInput,
  ListTasksQuery,
  Task,
  TaskAssignmentRole,
  TaskDomainEvent,
  TaskEventName,
  TaskId,
  TaskIdInput,
  TaskModel,
  TaskPermission,
  TaskPriority,
  TaskStatus,
  UnassignTaskInput,
  UpdateTaskInput,
} from "@/core/task";

export type {
  TaskRepository,
  TaskService,
} from "@/core/task/server";

export {
  TASK_EVENTS,
  TASK_PERMISSIONS,
  TASK_PRIORITIES,
  TASK_STATUSES,
  assignTaskSchema,
  createTaskSchema,
  listTasksQuerySchema,
  taskAssignmentRoleSchema,
  taskIdSchema,
  taskPrioritySchema,
  taskSchema,
  taskStatusSchema,
  unassignTaskSchema,
  updateTaskSchema,
} from "@/core/task";

export type {
  CreateDocumentInput,
  DeleteDocumentInput,
  Document,
  DocumentDomainEvent,
  DocumentEventName,
  DocumentId,
  DocumentIdInput,
  DocumentModel,
  DocumentPermission,
  DocumentRepository,
  DocumentService,
  DocumentStatus,
  DocumentWorkspaceKind,
  ListDocumentsQuery,
  UpdateDocumentInput,
} from "@/core/document";

export {
  DOCUMENT_EVENTS,
  DOCUMENT_PERMISSIONS,
  DOCUMENT_STATUSES,
  DOCUMENT_WORKSPACE_KINDS,
  createDocumentSchema,
  deleteDocumentSchema,
  documentIdSchema,
  documentSchema,
  documentStatusSchema,
  documentWorkspaceKindSchema,
  listDocumentsQuerySchema,
  updateDocumentSchema,
  validateCreateDocument,
  validateDeleteDocument,
  validateDocumentId,
  validateListDocumentsQuery,
  validateUpdateDocument,
} from "@/core/document";

export type {
  Budget,
  CreateFinanceInput,
  DeleteFinanceInput,
  Expense,
  Finance,
  FinanceCategory,
  FinanceDomainEvent,
  FinanceEventName,
  FinanceId,
  FinanceIdInput,
  FinanceModel,
  FinancePermission,
  FinanceService,
  FinanceStatus,
  FinanceType,
  Income,
  Invoice,
  ListFinanceQuery,
  Payment,
  Quotation,
  Refund,
  Transaction,
  UpdateFinanceInput,
} from "@/core/finance";

export {
  FINANCE_CATEGORIES,
  FINANCE_EVENTS,
  FINANCE_PERMISSIONS,
  FINANCE_STATUSES,
  FINANCE_TYPES,
  calculateBalance,
  calculateTax,
  calculateTotal,
  createFinanceSchema,
  deleteFinanceSchema,
  financeCategorySchema,
  financeIdSchema,
  financeSchema,
  financeStatusSchema,
  financeTypeSchema,
  listFinanceQuerySchema,
  updateFinanceSchema,
  validateCreateFinance,
  validateDeleteFinance,
  validateFinanceId,
  validateListFinanceQuery,
  validateUpdateFinance,
} from "@/core/finance";

export type {
  CreateNotificationInput,
  DeleteNotificationInput,
  ListNotificationsQuery,
  MarkAllNotificationsReadInput,
  MarkNotificationReadInput,
  Notification,
  NotificationChannel,
  NotificationDomainEvent,
  NotificationEventName,
  NotificationId,
  NotificationIdInput,
  NotificationMetadata,
  NotificationModel,
  NotificationPermission,
  NotificationPriority,
  NotificationRelatedEntityType,
  NotificationRepository,
  NotificationService,
  NotificationStatus,
  NotificationTemplate,
  NotificationTemplateKey,
  NotificationType,
  QueueNotificationInput,
  ScheduleNotificationInput,
  UpdateNotificationInput,
} from "@/core/notification";

export {
  NOTIFICATION_CHANNELS,
  NOTIFICATION_EVENTS,
  NOTIFICATION_PERMISSIONS,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_RELATED_ENTITY_TYPES,
  NOTIFICATION_STATUSES,
  NOTIFICATION_TEMPLATES,
  NOTIFICATION_TEMPLATE_KEYS,
  NOTIFICATION_TYPES,
  createNotificationSchema,
  deleteNotificationSchema,
  getNotificationTemplate,
  listNotificationsQuerySchema,
  markAllNotificationsReadSchema,
  markAllRead,
  markNotificationReadSchema,
  markRead,
  notificationChannelSchema,
  notificationIdSchema,
  notificationPrioritySchema,
  notificationRelatedEntityTypeSchema,
  notificationSchema,
  notificationStatusSchema,
  notificationTypeSchema,
  queueNotification,
  queueNotificationSchema,
  scheduleNotification,
  scheduleNotificationSchema,
  updateNotificationSchema,
  validateCreateNotification,
  validateDeleteNotification,
  validateListNotificationsQuery,
  validateNotificationId,
  validateUpdateNotification,
} from "@/core/notification";

export type {
  Automation,
  AutomationAction,
  AutomationActionType,
  AutomationCondition,
  AutomationConditionType,
  AutomationDomainEvent,
  AutomationEventName,
  AutomationExecution,
  AutomationExecutionStatus,
  AutomationId,
  AutomationIdInput,
  AutomationPermission,
  AutomationRepository,
  AutomationService,
  AutomationStatus,
  AutomationTrigger,
  AutomationTriggerType,
  AutomationType,
  CreateAutomationInput,
  DeleteAutomationInput,
  DisableAutomationInput,
  EnableAutomationInput,
  ListAutomationsQuery,
  Rule,
  UpdateAutomationInput,
  Workflow,
} from "@/core/automation";

export {
  AUTOMATION_ACTION_CATALOG,
  AUTOMATION_ACTION_TYPES,
  AUTOMATION_CONDITION_CATALOG,
  AUTOMATION_CONDITION_TYPES,
  AUTOMATION_EVENTS,
  AUTOMATION_EXECUTION_STATUSES,
  AUTOMATION_PERMISSIONS,
  AUTOMATION_STATUSES,
  AUTOMATION_TRIGGER_CATALOG,
  AUTOMATION_TRIGGER_TYPES,
  AUTOMATION_TYPES,
  createAutomationAction,
  createAutomationCondition,
  createAutomationSchema,
  createAutomationTrigger,
  deleteAutomationSchema,
  disableAutomationSchema,
  enableAutomationSchema,
  getAutomationActionDefinition,
  getAutomationConditionDefinition,
  getAutomationTriggerDefinition,
  listAutomationsQuerySchema,
  updateAutomationSchema,
  validateAction,
  validateAutomationId,
  validateCondition,
  validateDeleteAutomation,
  validateDisableAutomation,
  validateEnableAutomation,
  validateListAutomationsQuery,
  validateTrigger,
  validateUpdateAutomation,
  validateWorkflow,
} from "@/core/automation";

export type {
  Permission,
  PermissionAction,
  PermissionGrant,
  PermissionId,
  PermissionKey,
  PermissionRepository,
  PermissionResource,
  PermissionService,
  PlatformPermission,
} from "@/core/permission";

export {
  PERMISSION_ACTIONS,
  PERMISSION_RESOURCES,
  PLATFORM_PERMISSIONS,
  filterPlatformPermissions,
  hasAllPermissions,
  hasAnyPermission,
  hasPermission,
  isPlatformPermission,
  platformPermissionSchema,
  validateHasAllPermissions,
  validateHasAnyPermission,
  validateHasPermission,
  validatePermissionGrant,
} from "@/core/permission";

export type {
  CompanyContext,
  CompanyFilter,
  CompanyId,
  CompanyIsolationMode,
  CompanyIsolationRepository,
  CompanyIsolationService,
  CompanyScope,
  CompanyScoped,
  CurrentCompany,
  IsolationGuardResult,
} from "@/core/company-isolation";

export {
  COMPANY_ISOLATION_MODES,
  COMPANY_SCOPE_FIELD,
  applyCompanyFilter,
  applyCompanyScope,
  assertCompanyBoundary,
  assertRecordCompany,
  assertSameCompany,
  checkCompanyIsolation,
  companyIdSchema,
  companyScopeField,
  filterByCompany,
  guardCompanyId,
  isCompanyScoped,
  requireCompany,
  toCompanyFilter,
  toCompanyScope,
  validateCompanyContext,
  validateCompanyFilter,
  validateCompanyScope,
  validateCurrentCompany,
} from "@/core/company-isolation";

export type {
  EffectivePermissions,
  RbacRoleAssignment,
  RbacRoleDefinition,
  RbacRoleKey,
  RBACRepository,
  RBACService,
} from "@/core/rbac";

export {
  DEFAULT_RBAC_ROLES,
  RBAC_ROLES,
  RBAC_ROLE_LABELS,
  canManageCompany,
  canManageWorkspace,
  getRolePermissions,
  hasRole,
  hasRolePermission,
  isAdmin,
  isOwner,
  isRbacRoleKey,
  listRbacRoles,
  resolveEffectivePermissions,
  validateHasRole,
  validateHasRolePermission,
  validateRbacRoleAssignment,
  validateRbacRoleKey,
  validateResolveEffectivePermissions,
} from "@/core/rbac";

export type {
  CreateStorageObjectInput,
  ListStorageObjectsQuery,
  StorageBucket,
  StorageObject,
  StorageObjectId,
  StorageRepository,
  StorageService,
  StorageVisibility,
  ValidatedUpload,
} from "@/core/storage";

export {
  DEFAULT_MAX_FILE_SIZE_BYTES,
  STORAGE_BUCKETS,
  STORAGE_VISIBILITIES,
  buildStoragePath,
  generateStorageKey,
  normalizeStoragePath,
  resolveBucket,
  validateExtension,
  validateFileSize,
  validateFilename,
  validateMimeType,
  validateUpload,
} from "@/core/storage";

export type {
  CreateSearchObjectInput,
  PreparedSearch,
  SearchEntityType,
  SearchHit,
  SearchObject,
  SearchQueryInput,
  SearchRepository,
  SearchService,
} from "@/core/search";

export {
  SEARCH_ENTITY_TYPES,
  SEARCH_FILTERS,
  buildSearchDocument,
  buildSearchIndex,
  extractKeywords,
  normalizeQuery,
  prepareSearch,
  rankResults,
  tokenizeKeywords,
  validateSearchQuery,
} from "@/core/search";

export type {
  AuditAction,
  AuditActorType,
  AuditChange,
  AuditEntityType,
  AuditRecord,
  AuditRepository,
  AuditService,
  CreateAuditRecordInput,
  ListAuditRecordsQuery,
} from "@/core/audit";

export {
  AUDIT_ACTIONS,
  AUDIT_ACTOR_TYPES,
  AUDIT_ENTITY_TYPES,
  AUDIT_EVENTS,
  buildAuditRecord,
  compareChanges,
  normalizeAction,
  prepareMetadata,
  sanitizeMetadata,
  validateAuditRecord,
} from "@/core/audit";

export { CoreError, toCoreUserMessage } from "@/core/errors";

export {
  ACTIVE_WORKSPACE_COOKIE,
  listWorkspacesForUser,
  resolveActiveWorkspace,
  switchActiveWorkspace,
} from "@/core/workspace/active-workspace";
